# Generated by Django 5.1.4 on 2024-12-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя', max_length=30, verbose_name='Имя')),
                ('email', models.EmailField(help_text='Почта', max_length=50, verbose_name='Почта')),
                ('address', models.CharField(help_text='Адрес', max_length=50, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Сумма', verbose_name='Сумма')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laba_6.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Сумма', verbose_name='Сумма')),
                ('purpose', models.CharField(help_text='Цель кредита', max_length=50, verbose_name='Цель кредита')),
                ('submitted_on', models.DateField(help_text='Представлено', verbose_name='Представлено')),
                ('disbursement_on', models.DateField(help_text='Выплата по', verbose_name='Выплата по')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laba_6.customer')),
            ],
        ),
    ]
